/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'status' : OrderStatus,
  'userId' : Principal,
  'productId' : ProductId,
  'orderId' : OrderId,
  'timestamp' : Time,
}
export type OrderId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'driveLink' : string,
  'category' : string,
  'price' : bigint,
}
export type ProductId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, string, string],
    ProductId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmOrder' : ActorMethod<[OrderId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'editProduct' : ActorMethod<
    [ProductId, string, string, bigint, string, string, boolean],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[ProductId], OrderId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];